[window]
padding = { x = 10, y = 10 }
opacity = 0.75
startup_mode = "Windowed"
dynamic_title = true
class = { instance = "Alacritty", general = "Term" }

[scrolling]
history = 8196

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style="Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style="ExtraBold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style="Italic" }
size = 11

[colors]
transparent_background_colors = true

[cursor]
style = { shape = "Beam", blinking = "On"}
blink_timeout = 15
thickness = 0.25

[keyboard]
bindings = [{ key = "F", mods = "Alt|Control", action = "CreateNewWindow"}] # there probably is a default bind for that already but i`m too lazy to search for it

[debug]
# render_timer = true
persistent_logging = true

[general]
live_config_reload = true

[terminal]
shell = "zsh"
# highlight_damage = true # this is funny
